"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u0%p%o8gmfz591y^-7zq0^81kmd675x*s=aw#(#eb0z35i#k=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'home.apps.HomeConfig',
    'accounts.apps.AccountsConfig',
    'orders.apps.OrdersConfig',

    # Third-party apps
    'django_celery_beat',
    'storages',
    'ckeditor',
]   

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'psdb',
        'USER': 'postgres',
        'PASSWORD':'root',
        'HOST':'127.0.0.1',
        'PORT':'5432',

    }
}
"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Media Files
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
# if we use our customized User model, we must define AUTH_USER_MODEL = "<app_name>.<model_name>"

STATICFILES_STORAGE = "storages.backends.s3.S3Storage"
# STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# ParsPack storages
AWS_ACCESS_KEY_ID = 'EJb9wmgWaXK8IPAB'
AWS_SECRET_ACCESS_KEY = 'nIkAWhUKjO3EFvrUmnEcKbwT63Kh7PdK'
AWS_S3_ENDPOINT_URL = 'https://c999265.parspack.net'
AWS_STORAGE_BUCKET_NAME = 'c999265'
"""
# ArvanCloud storages
AWS_ACCESS_KEY_ID = '50b1cc4f-5e03-4e07-b338-180bf51e38d8'
AWS_SECRET_ACCESS_KEY = 'c699d522bb40716be90aabf22e388cd68ecb82c244624c67c766ee730c67ac82'
AWS_S3_ENDPOINT_URL = 'https://s3.ir-thr-at1.arvanstorage.ir'
AWS_STORAGE_BUCKET_NAME = 'shop-ash'
"""
AWS_S3_REGION_NAME = 'default'
AWS_QUERYSTRING_AUTH = False
AWS_SERVICE_NAME = 's3'
AWS_S3_FILE_OVERWRITE = False
AWS_LOCAL_STORAGE = f'{BASE_DIR}/aws/'
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_S3_SIGNATURE_VERSION = 's3v4'

# ASYNC with Celery
CELERY_IS_ACTIVE = True


# ZARRINPAL - SANDBOX MODE
MERCHANT = '107ba161-13a7-47f1-b92d-54d6f7fad277'
SANDBOX = True

# CAN CHANGE SUPERUSER FIELD
CCSF = False

# CK_EDITOR CONFIGS
CKEDITOR_CONFIGS = {
    'default':{'toolbar': 'full'},
}

# Google account (forget password)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ash6218@gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_PASSWORD = 'wnsmkrvzrbiqykhp'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Ash1.ir'