# Generated by Django 5.2.1 on 2025-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('postal_code', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
