# Generated by Django 5.2.1 on 2025-07-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userupdateprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpdateProfile',
        ),
    ]
