# Generated by Django 5.2.1 on 2025-07-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_is_sub_category_scategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='scategory',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='home.category'),
        ),
    ]
