# Generated by Django 5.2.1 on 2025-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_category_scategory_category_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
