# Generated by Django 5.2.1 on 2025-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
